import { useState, useEffect } from 'react'
import { supabase } from '../lib/supabaseClient'
import { useAuth } from '../contexts/AuthContext'

export function useBookings() {
  const { user } = useAuth()
  const [bookings, setBookings] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (user) {
      fetchBookings()
    } else {
      setBookings([])
      setLoading(false)
    }
  }, [user])

  const fetchBookings = async () => {
    if (!user) return

    setLoading(true)
    const { data, error } = await supabase
      .from('bookings')
      .select(`
        *,
        event:events(*)
      `)
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })

    if (!error && data) {
      setBookings(data)
    } else if (error) {
      console.error('Error fetching bookings:', error)
    }
    setLoading(false)
  }

  const createBooking = async (bookingData) => {
    if (!user) {
      return { data: null, error: new Error('Must be logged in to create booking') }
    }

    const { data, error } = await supabase
      .from('bookings')
      .insert([{
        ...bookingData,
        user_id: user.id,
        confirmation_code: '' // Will be auto-generated by trigger
      }])
      .select(`
        *,
        event:events(*)
      `)
      .single()

    if (!error && data) {
      await fetchBookings()
    }

    return { data, error }
  }

  const cancelBooking = async (bookingId) => {
    if (!user) {
      return { data: null, error: new Error('Must be logged in') }
    }

    const { data, error } = await supabase
      .from('bookings')
      .update({ status: 'cancelled' })
      .eq('id', bookingId)
      .eq('user_id', user.id) // Security check
      .select()
      .single()

    if (!error && data) {
      await fetchBookings()
    }

    return { data, error }
  }

  return {
    bookings,
    loading,
    createBooking,
    cancelBooking,
    refetch: fetchBookings
  }
}
